apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
    name: oootp
    namespace: oootp
spec:
    network:
        serviceMesh:
            mode: ambient
        expose:
            - gateway: tenant
              host: oootp
              podLabels:
                app.kubernetes.io/name: frontend
              port: 8080
              selector:
                app.kubernetes.io/name: frontend
              service: frontend
        allow:
            - direction: Ingress
              remoteGenerated: IntraNamespace
            - direction: Egress
              remoteGenerated: IntraNamespace
            - direction: Egress
              remoteNamespace: postgres
              remoteSelector:
                cluster-name: pg-cluster
              port: 5432
              description: postgres-operator managed cluster
    sso:
        - clientId: oootp
          name: Oootp
          redirectUris:
            - https://frontend.uds.dev/*
