name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: UDS CLI Setup
        uses: defenseunicorns-udm/udm-common/.github/actions/uds-cli-setup@545eadfb425e52e818cce5f28b4d046f5cd4e15d # v0.9.1

      - name: Lint
        run: uds run attest:lint

      - name: Security Scan
        run: |
          uds run scan:security \
            --with opengrep_scan_path=apps/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build Docker images
        run: uds run build-images

      - name: Vouch
        # if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          uds run vouch:package \
            --with github_token="${{ secrets.GITHUB_TOKEN }}" \
            --with olm_cat=cat-api.uds-mil.us \
            --with olm_org=uds-army-demo \
            --with attestations="lint-witness.json,gitleaks-witness.json,opengrep-witness.json" \
            --with sarif_files="gitleaks.sarif.json,opengrep.sarif.json"

      - name: Publish
        # if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          uds run publish:zarf-package \
            --with registry=registry.uds-mil.us \
            --with registry_org=uds-army-demo \
            --with registry_user_id="${{ secrets.REGISTRY_USER_ID }}" \
            --with registry_password="${{ secrets.REGISTRY_PASSWORD }}"
